# Generated by Django 5.1.5 on 2025-02-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_paper_delete_blog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Paper",
            new_name="Blog",
        ),
    ]
