# Generated by Django 5.1.5 on 2025-02-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_paper_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/", verbose_name="Превью"
            ),
        ),
    ]
