# Generated by Django 5.1.5 on 2025-02-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog/media/images/",
                verbose_name="Изображение продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Введите стоимость покупки", max_digits=100
            ),
        ),
    ]
